/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import static UI.SignUpPanel.Role;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
/**
 *
 * @author aravind
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    PersonDirectory personDirectory;
    private JSplitPane SplitPane;
    PatientDirectory patientDirectory;
    static String Role = "";
    
    public LoginPanel(JSplitPane SplitPane, PatientDirectory patientDirectory, PersonDirectory personDirectory) {
        initComponents();
        licenseLabel.setVisible(false);
        licenseField.setVisible(false);
        this.personDirectory = personDirectory;
        this.SplitPane = SplitPane;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        licenseLabel = new javax.swing.JLabel();
        licenseField = new javax.swing.JTextField();
        doctorRadio = new javax.swing.JRadioButton();
        patientRadio = new javax.swing.JRadioButton();
        btnView = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        userNameLabel.setText("Username");

        passwordLabel.setText("Password");

        licenseLabel.setText("License Number");

        buttonGroup2.add(doctorRadio);
        doctorRadio.setText("Doctor");
        doctorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(patientRadio);
        patientRadio.setText("Patient");
        patientRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRadioActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licenseLabel)
                            .addComponent(userNameLabel)
                            .addComponent(passwordLabel))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(licenseField)
                            .addComponent(userNameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(doctorRadio)
                        .addGap(52, 52, 52)
                        .addComponent(patientRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnView)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseLabel)
                    .addComponent(licenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorRadio)
                    .addComponent(patientRadio))
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorRadioActionPerformed
        if(doctorRadio.isSelected() == true){
            licenseLabel.setVisible(true);
            licenseField.setVisible(true);
            Role = "Doctor";
        }
    }//GEN-LAST:event_doctorRadioActionPerformed

    private void patientRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRadioActionPerformed
        if(patientRadio.isSelected() == true){
            licenseLabel.setVisible(false);
            licenseField.setVisible(false);
            Role = "Patient";
        }
    }//GEN-LAST:event_patientRadioActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        if(Role=="Doctor")
        {
//            Person p = personDirectory.addNewPerson();
            
            String SearchEmail = userNameField.getText();
            char SearchPass[] = passwordField.getPassword();
            for(Person prn: personDirectory.getPersonDirectory()){
                if(prn.getEmail().equals(SearchEmail) && java.util.Arrays.equals(prn.getPassword(),SearchPass))
                {
                    ViewPerson viewPersonDetails = new ViewPerson(SplitPane,personDirectory,patientDirectory);
                    SplitPane.setRightComponent(viewPersonDetails);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Select a row to view or update it.");
                }
//           if(i.getUsername().equals(jTextField10.getText())){
//               
//              System.out.println(i.getUsername());
//               
//               jTabbedPane1.setSelectedIndex(8);
//           }
//           else if(jTextField10.getText().isEmpty()||jPasswordField4.getText().isEmpty()){
//               JOptionPane.showMessageDialog(this,"Enter credentials");
//           }
//            else{
//               JOptionPane.showMessageDialog(this,"username not found");
//           }
           
       }
        }
        else if(Role=="Patient")
        {
            ViewPerson viewPersonDetails = new ViewPerson(SplitPane,personDirectory,patientDirectory);
            SplitPane.setRightComponent(viewPersonDetails);
        }
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnView;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton doctorRadio;
    private javax.swing.JTextField licenseField;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JRadioButton patientRadio;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
