/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
/**
 *
 * @author aravind
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    PersonDirectory personDirectory;
    private JSplitPane SplitPane;
    PatientDirectory patientDirectory;
    String SearchEmail;
    int i;
    static String Role = "";
    String str = "root";
    String str1 = "croot";
    char[] compareString1 = str1.toCharArray();
    char[] compareString = str.toCharArray();
    
    public LoginPanel(JSplitPane SplitPane, PatientDirectory patientDirectory, PersonDirectory personDirectory) {
        initComponents();
        licenseLabel.setVisible(false);
        licenseField.setVisible(false);
        this.personDirectory = personDirectory;
        this.SplitPane = SplitPane;
        this.patientDirectory = patientDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        licenseLabel = new javax.swing.JLabel();
        licenseField = new javax.swing.JTextField();
        doctorRadio = new javax.swing.JRadioButton();
        patientRadio = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();

        userNameLabel.setText("Username");

        passwordLabel.setText("Password");

        licenseLabel.setText("License Number");

        buttonGroup2.add(doctorRadio);
        doctorRadio.setText("Doctor");
        doctorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorRadioActionPerformed(evt);
            }
        });

        buttonGroup2.add(patientRadio);
        patientRadio.setText("Patient");
        patientRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRadioActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licenseLabel)
                            .addComponent(userNameLabel)
                            .addComponent(passwordLabel))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(licenseField)
                            .addComponent(userNameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(doctorRadio)
                        .addGap(52, 52, 52)
                        .addComponent(patientRadio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(btnLogin)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseLabel)
                    .addComponent(licenseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorRadio)
                    .addComponent(patientRadio))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorRadioActionPerformed
        if(doctorRadio.isSelected() == true){
            licenseLabel.setVisible(true);
            licenseField.setVisible(true);
            Role = "Doctor";
        }
    }//GEN-LAST:event_doctorRadioActionPerformed

    private void patientRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRadioActionPerformed
        if(patientRadio.isSelected() == true){
            licenseLabel.setVisible(false);
            licenseField.setVisible(false);
            Role = "Patient";
        }
    }//GEN-LAST:event_patientRadioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        SearchEmail = userNameField.getText();
            char SearchPass[] = passwordField.getPassword();
            Integer temp = 0;
            if(SearchEmail.length() == 0 || SearchPass[0] == 0)
                {
                    JOptionPane.showMessageDialog(this, "Username or Password is Empty");
                }
            else {
        if(Role=="Doctor")
        {   
//            Person prn;
//            Person prn = new Person();
            {
                for(Person prn :  personDirectory.getPersonDirectory()){
                    if(prn.getEmail().equals(SearchEmail) && java.util.Arrays.equals(prn.getPassword(),SearchPass))
                    {
                        ViewPerson viewPersonDetails = new ViewPerson(SplitPane,personDirectory,patientDirectory,SearchEmail,Role);
                        SplitPane.setRightComponent(viewPersonDetails);
                        temp=1;
                        break;
                    }
                }
                if(temp==0)
                {
                    JOptionPane.showMessageDialog(this, "Username or Password does not match");
                }
            }
        }
        else if(Role=="Patient")
        {
            {
                for(Person p :  personDirectory.getPersonDirectory()){
                    if(p.getEmail().equals(SearchEmail) && java.util.Arrays.equals(p.getPassword(),SearchPass))
                    {
                        appointmentBooking aptBook = new appointmentBooking(SplitPane,personDirectory,patientDirectory,SearchEmail,Role);
                        SplitPane.setRightComponent(aptBook);
                        temp=1;
                        break;
                    }
                }
                if(temp==0)
                {
                    JOptionPane.showMessageDialog(this, "Username or Password does not match");
                }
            }
        }
        else if(Role=="" && userNameField.getText().equals("root") && java.util.Arrays.equals(compareString,SearchPass))
        {
            ViewPerson viewPersonDetails = new ViewPerson(SplitPane,personDirectory,patientDirectory,SearchEmail,Role);
            SplitPane.setRightComponent(viewPersonDetails);
        }
        else if(Role=="" && userNameField.getText().equals("croot") && java.util.Arrays.equals(compareString1,SearchPass))
        {
            CommunitySearch cSearch = new CommunitySearch(SplitPane,patientDirectory,personDirectory,SearchEmail,str1);
            SplitPane.setRightComponent(cSearch);
        }
            }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton doctorRadio;
    private javax.swing.JTextField licenseField;
    private javax.swing.JLabel licenseLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JRadioButton patientRadio;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
